name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/my-app
            if [ ! -d ".git" ]; then
              git clone https://github.com/harshithabg333/Streamlit-Python.git .
            else
              git pull origin main
            fi
            pip install -r requirements.txt
            pkill -f streamlit || true
            nohup streamlit run form_app_2.py --server.port 8501 &