name: Test Secrets
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets
        run: |
          echo "Host is: ${{ secrets.EC2_HOST }}"
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "Error: Host is EMPTY"
          else
            echo "Success: Host is set"
          fi